services:
  - type: web
    name: wel-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_BASIC_PRICE_ID
        sync: false
      - key: STRIPE_PRO_PRICE_ID
        sync: false
